class BossTuning:
    HITBOX_WIDTH = 80
    HITBOX_HEIGHT = 105

    IMAGE_VERTICAL_OFFSET = 26
    HITBOX_FORWARD_OFFSET = 12
    STALK_SPEED = 150.0

    # Boss approaches until Freddy is within this distance.
    CHARGE_TRIGGER_DISTANCE = 340.0

    # Boss pauses at range before committing to the rush.
    CHARGE_TELEGRAPH_DURATION = 0.50

    CHARGE_SPEED = 580.0
    CHARGE_DURATION = 0.65

    RECOVERY_DURATION = 0.90

    ANIMATION_INTERVAL = 0.24

    CONTACT_DAMAGE = 2

    DEBUG_COLOR = (255, 70, 70)

    MAX_HEALTH = 20

    DEATH_DISPLAY_DURATION = 0.8

    LEAP_TRIGGER_HEIGHT = 70.0

    LEAP_HORIZONTAL_SPEED = 260.0
    LEAP_VERTICAL_SPEED = 650.0

    GRAVITY = 1800.0
    MAX_FALL_SPEED = 900.0

    SPRITE_SCALE = 1.25

    SWORD_HIT_STAGGER_DURATION = 0.18
    SWORD_HIT_KNOCKBACK_SPEED = 90.0

    FIREBALL_HIT_FLASH_DURATION = 0.10
    SWORD_HIT_FLASH_DURATION = 0.16

    PLATFORM_IMAGE_VERTICAL_OFFSET = 8